# Generated by Django 3.1 on 2021-05-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0003_auto_20210508_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinissues',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bulletinissues',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bulletinissues',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='companies',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='konkurzrestrukturalizaciaactors',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='konkurzrestrukturalizaciaactors',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='konkurzrestrukturalizaciaissues',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='konkurzrestrukturalizaciaissues',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='konkurzrestrukturalizaciaproposings',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='konkurzrestrukturalizaciaproposings',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='konkurzvyrovnanieissues',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='konkurzvyrovnanieissues',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='likvidatorissues',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='likvidatorissues',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orpodanieissuedocuments',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orpodanieissuedocuments',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rawissues',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rawissues',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='znizenieimaniaceos',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='znizenieimaniaceos',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='znizenieimaniaissues',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='znizenieimaniaissues',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
